### ISSUE TITLE
tiny olead

### ISSUE THREAD

**Issue by Giancky79** [adonno/tagreader#101]
Hi, i'm try to work with a tiny olead 0,94 for info, from esphome i don't found anything for address option, but for rc522 i have on DOC, the voice
```
I²C Only:
  address
```
now i found the address for pn532, 0x48, for an evolution of your tag reader, is possible? with this solution we can pilote both component from sda-scl

**Comment by jesserockz** [comment]
I2C is capable of hosting multiple devices on the same 2 SDA/SCL wires using addresses. So yes you can reuse the wires and have both the pn532 and your oled at the same time

**Comment by zuidwijk** [comment]
... as long both devices don't have the same address 😉
