### ISSUE TITLE
Unable to Flash

### ISSUE THREAD

**Issue by seanmccabe** [adonno/tagreader#103]
Hi there,

I am totally new to this and done my best to Google and try and figure this out.

I have wired everything up, and plyggin power into the board via USB both the boards light up, but I am having issues flashing this.

In ESPHome home in Docker I've copied in the tagreader.yaml and compiled. Plug the board in by USB and can see USB Serial.

Attempt to then upload over USB and get the following:

```
INFO Successfully compiled program.
INFO Running:  esptool.py --before default_reset --after hard_reset --baud 460800 --chip esp8266 --port /dev/ttyUSB0 write_flash 0x0 /config/tagreader/.pioenvs/tagreader/firmware.bin
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP8266: Timed out waiting for packet header
INFO Upload with baud rate 460800 failed. Trying again with baud rate 115200.
INFO Running:  esptool.py --before default_reset --after hard_reset --baud 115200 --chip esp8266 --port /dev/ttyUSB0 write_flash 0x0 /config/tagreader/.pioenvs/tagreader/firmware.bin
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP8266: Timed out waiting for packet header
```

Really don't know what I am doing wrong here, and everything I Google just confuses me more, so looking for some plain english help.

Thanks!

**Comment by zuidwijk** [comment]
Error message is easy: it can't connect.  

Either a faulty esp, or there is something connected to the rx or tx, or the usb chip is faulty. 

Either way... no connection between the esp and usb chip

**Comment by seanmccabe** [comment]
Definately nothing in the rx or tx, completely untouched.
Will try flashing another unwired (didnt realise you could do this).

Thanks.

**Comment by seanmccabe** [comment]
Ok, deffo faulty chip, or something else isnt quite right.
As just flashed an unsoldered unit without issue.

Maybe just to check Im doing this right (long time since I've done electronics).
The 5v line, is that one cable to the LED, and one to the PN532 yes? Both just soldered at the 5v terminal on the D1 mini.

**Comment by zuidwijk** [comment]
Now I do remember that a faulty led could cause this too. In that case, unsolder the led. See if it works.

**Comment by seanmccabe** [comment]
OK so second attempt at soldering, programmed beforehand, finished soldering and doesn't work.
Anyone see what I'm doing wrong, I'm not the best, but can't see any glaring issues...

![20210328_150858.jpg](https://user-images.githubusercontent.com/12243212/112740220-abeb5780-8fd7-11eb-872e-bccbb1191af1.jpg)
![20210328_150846.jpg](https://user-images.githubusercontent.com/12243212/112740224-aee64800-8fd7-11eb-9d75-43c67271753a.jpg)
![20210328_150800.jpg](https://user-images.githubusercontent.com/12243212/112740237-c1f91800-8fd7-11eb-8e93-3a961640265a.jpg)
![20210328_150739.jpg](https://user-images.githubusercontent.com/12243212/112740240-c6bdcc00-8fd7-11eb-91da-0c35583f5917.jpg)![20210328_150438.jpg](https://user-images.githubusercontent.com/12243212/112740243-cb828000-8fd7-11eb-902e-117a5e16c3e3.jpg)![20210328_150400.jpg](https://user-images.githubusercontent.com/12243212/112740244-ccb3ad00-8fd7-11eb-8608-3f3f3971ef1c.jpg)![20210328_150353.jpg](https://user-images.githubusercontent.com/12243212/112740245-cde4da00-8fd7-11eb-953b-fb46d9d2c8a1.jpg)![20210328_150340.jpg](https://user-images.githubusercontent.com/12243212/112740246-cf160700-8fd7-11eb-8089-307e8ddf523c.jpg)

**Comment by seanmccabe** [comment]
> Now I do remember that a faulty led could cause this too. In that case, unsolder the led. See if it works.

Ok, turns out yes, it is the LED, am i soldering it wrong? Just to make sure before i return them as faulty.

Also, is there a way to solder it in the meantime without the LED?

**Comment by seanmccabe** [comment]
Sorted
