### ISSUE TITLE
NFC Card with two Tag IDs

### ISSUE THREAD

**Issue by cloudhaus** [adonno/tagreader#110]
I have received my Adonno tag reader in the mail. I now have it integrated into Home Assistant. 

I have an NFC card that when I scan can give two different Tag Ids in Home Assistant. 

Sometimes when I scan the card it gives
Tag ID: 62537fed-6852-40fe-bffd-7c9ab8600dfc

Other times when I scan it the card send to Home Assistant
Tag ID: 04-F6-D9-F2-1F-68-80

It is only these two Tag IDs that are sent to Home Assistant. There is no consistency with the ID that is sent, it can be either and I am not able to predict.

Do I need to write my automations that can handle either Tag ID for this card or am I doing something wrong / missing some configuration somewhere?

Thank you!

**Comment by adonno** [comment]
I'd suggest you go to your developer tools, and chose write_tag_id

![image](https://user-images.githubusercontent.com/13216947/116774532-7b2a9200-aa5d-11eb-9b00-fb2a0fd84c8c.png)

**Comment by jesserockz** [comment]
I think the issue here is that sometimes it can read the ndef uuid, and sometimes it fails, and falls back to the card uid
