### ISSUE TITLE
Can't compile - error in example code?

### ISSUE THREAD

**Issue by zygote279** [adonno/tagreader#120]
Hi there,

Following this tutorial and trying to validate the example code you post here: https://github.com/adonno/tagreader/blob/master/tagreader.yaml

Not entirely sure what you mean by 'point esphome here', but have tried copying/pasting this code into my esphome instance (and updating the details, eg SSID/PWD) and it returns the following error:

`
[name_add_mac_suffix] is an invalid option for [esphome]. Please check the indentation.
  name_add_mac_suffix: True
  
  [project] is an invalid option for [esphome]. Please check the indentation.
`

Is there something daft I'm missing here?

**Comment by adonno** [comment]
what version of esphome are you using?  make sure t have the latest

**Comment by adonno** [comment]
no reply in 60 days, issue closed
