### ISSUE TITLE
Compatiblility with ESP32 and the PN7150 NFC tag reader used in "Chhavi" (crowdfunding campaign product on on Crowd Supply)

### ISSUE THREAD

**Issue by Hedda** [adonno/tagreader#134]
Do you think that the NXP PN7150 module based NFC tag reader used in this ESP32-based "Chhavi" product with fingerprint sensor and optional NFC tag reader can be supported in ESPHome on this and then be made to work with [Home Assistant Tags](https://www.home-assistant.io/blog/2020/09/15/home-assistant-tags/) project?

https://www.crowdsupply.com/vicharak/chhavi

Vicharak has launched "Chhavi" ESP32 based fingerprint and NFC reader product as a crowdfunding campaign on Crowd Supply. 

"Chhavi is a compact, wireless, touch-capacitive fingerprint sensor based on ESP32 WiFi and Bluetooth SoC that is offered with optional NFC connectivity and a battery." 

It says that it can also optionally be powered by a battery.

Not cheap but it have to say that its very compact size makes it looks very nice. BTW, I first read about it on CNX-Software blog:

https://www.cnx-software.com/2021/10/08/chhavi-esp32-fingerprint-sensor-nfc-battery/

"FPC BM-Lite" fingerprint sensor module by Fingerprints 

https://www.fingerprints.com/technology/hardware/modules/fpc-bm-lite/

https://www.fingerprints.com/solutions/access/bm-lite-development-kit/

NXP "PN7150 NFC controller"

https://www.nxp.com/products/rfid-nfc/nfc-hf/nfc-readers/high-performance-nfc-controller-with-integrated-firmware-for-smart-devices:PN7150

https://www.nxp.com/docs/en/data-sheet/PN7150.pdf

#### NFC Specifications & RF Protocols
 - PN7150 NFC controller
 - NFCIP-1 ¹ & NFCIP-2 ²
 - ISO/IEC 14443A, ISO/IEC 14443B PICC, and NFC Forum T4T modes via host interface ³
 - NFC Forum T3T via host interface
 - ISO/IEC 14443A, ISO/IEC 14443B PCD designed according to NFC Forum digital protocol T4T platform and ISO-DEP ⁴
 - FeliCa PCD mode
 - MIFARE Classic PCD encryption mechanism (MIFARE Classic 1K/4K)
 - NFC Forum tag 1 to 5 (MIFARE Ultralight, Jewel, Open FeliCa tag, MIFARE DESFire) ¹
 - ISO/IEC 15693/ICODE VCD mode ⁵
 - Supports card emulation as well as reader mode

¹ ISO/IEC 18092 (NFCIP-1) edition, 2013-03-15. This is similar to Ecma 340
² ISO/IEC 15693 part 2: 2nd edition (2006-12-15), part 3: 1st edition (2001-04-01)
³ ISO/IEC 14443 parts 2: 2001 COR 1 2007 (2007-11-01), part 3: 2001 COR 1 2006 (2006-09-01) and part 4: 2nd edition 2008 (2008-07-15)
⁴ NFC Forum Device Requirements V1.3
⁵ ISO/IEC 15693 part 2: 2nd edition (2006-12-15), part 3: 1st edition (2001-04-01)

PS: I'm just a home automation enthusiast and have no affiliations or connections with Chhavi and Crowd Supply or any others.

**Comment by adonno** [comment]
Wow that looks amazing 
This is what you can achieve when you have the right knowledge

**Comment by akshar001** [comment]
@Hedda yes i will submit a Chhavi NFC in ESPHome

**Comment by akshar001** [comment]
We have integrated the ESPhome with chhavi i will send you a repo soon.

**Comment by Hedda** [comment]
@adonno Is PN7150 (and thus also Chhavi hardware) now supported by your tagreader project?

**Comment by adonno** [comment]
No actually These are two different Projects. 
My that would require a complete different yaml . right now PN7150 isn't supported buy ESPHome at all. For the rest you will be able to copy the Tag segment. 

Therefore i closed the issue.
