### ISSUE TITLE
Edit .YAML in ESPHome in HA

### ISSUE THREAD

**Issue by Rowleys** [adonno/tagreader#144]
Hi, When I go to edit the YAML in HA it just shows this ..

`substitutions:
  name: tagreader-db4ead
packages:
  adonno.tag_reader: github://adonno/tagreader/tagreader.yaml
esphome:
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password`
  
  Is this right ?
  
  Thanks

**Comment by adonno** [comment]
Hello, 

yes, that is right. 
ESPHome can't load the code that actually runs on the device, but it can identify it and knows that it's related to the tag reader project on GitHub. 

so whenever you flash your device it goes on GitHub pulls the default YAML from there and your changes will overrule the default YAML . Say you want to add a sensor? No need to copy the whole YAML, add the sensor and you should be good to go
