### ISSUE TITLE
Living Room Restart

### ISSUE THREAD

**Issue by fbonomini** [adonno/tagreader#149]
I think there is an error in tagreader.yaml file,

the section
  - platform: restart
    name: "Living Room Restart"
    entity_category: config

should be
  - platform: restart
  name: "${friendly_name} Restart"
    entity_category: config

Thanks for all the good work with this project!
Flavio.

**Comment by adonno** [comment]
that is actually an issue:-D it's because I copy-pasted it from the ESPHome website  will fix it right away

**Comment by adonno** [comment]
thank you again fixed now :-D 
now let's reflash the new devices
