### ISSUE TITLE
ESPHome 2022.2

### ISSUE THREAD

**Issue by BeardedTinker** [adonno/tagreader#152]
Will there be update for FastLED and 2022.2 for the project?

> FastLED(https://esphome.io/changelog/2022.2.0.html#fastled)
> Due to the Arduino bump, the FastLED library suffers issues when running on ESP8266 on Arduino 3+. Because of this there is now a restriction on the fastled_clockless and fastled_spi components to only allow using them if you change the arduino version back to 2.7.4 or lower. This will be in place until the library can update and fix the issues. See the [documentation](https://esphome.io/components/light/fastled.html) for information on how to continue using the lights.

```
light.fastled_clockless: [source /config/esphome/tagreader.yaml:117]
  
  This feature requires framework version 2.7.4 or lower. Please see note on documentation for FastLED.
  platform: fastled_clockless
  chipset: WS2812
  pin: D8
  default_transition_length: 10ms
  num_leds: 1
  rgb_order: GRB
  id: activity_led
  name: TagReader LED
  restore_mode: ALWAYS_OFF
```
Or should we for now wait until library issue is resolved.

**Comment by adonno** [comment]
Replaces FastLED with NeoPixelBus
