### ISSUE TITLE
Use TagReader with ESPHome & ioBroker

### ISSUE THREAD

**Issue by serb91** [adonno/tagreader#161]
Hi,
is it possible to the TagReader with ESPHome in ioBroker?
I don't use Homeassistant but i want to try to integrate your project in my smarthome via iobroker :-)

I try to flash my ESP8266 but i get this:

![image](https://user-images.githubusercontent.com/94891097/159754912-60c92b2d-d2ee-47b1-86b1-0be68a5d3440.png)

can you show me what i have to change?
thx!

**Comment by adonno** [comment]
I am working on a MQTT version as well 
does iobroker support espHome?

**Comment by serb91** [comment]
> I am working on a MQTT version as well
> does iobroker support espHome?

Yes, iobroker support esphome. 
a mqtt version will be also great

**Comment by adonno** [comment]
so all i can do with MQTT right now is get the TAG ID no NDEF messages (i could i guess but i need some time ). is that ok ?

**Comment by adonno** [comment]
can you try installing the following 
https://github.com/adonno/tagreader/pull/164/files

**Comment by adonno** [comment]
no replies
