### ISSUE TITLE
Invalid object error

### ISSUE THREAD

**Issue by matat60** [adonno/tagreader#163]
![Capture d’écran 2022-03-21 115312](https://user-images.githubusercontent.com/72278357/159247387-fedb3bc0-64dd-4734-b06a-14ef66a32d46.png)
Here my issue

_Originally posted by @matat60 in https://github.com/adonno/tagreader/issues/158#issuecomment-1073753649_

**Comment by adonno** [comment]
sorry for asking but did you have esphome installe dprior and di you have a tagreader already configured ?

**Comment by adonno** [comment]
you have to delete it from esphome. 
maybe also flash it from https://adonno.github.io/tagreader

**Comment by matat60** [comment]
Having the same error with flashing by chrome.

**Comment by adonno** [comment]
do you have already a tag reader installed in esphome ?  
if so delete it and readapt it please

**Comment by adonno** [comment]
do you use custom DNS ? or firewalls ?

**Comment by adonno** [comment]
no reply
