### ISSUE TITLE
Can't get any NFC reading

### ISSUE THREAD

**Issue by mjvanderveen** [adonno/tagreader#165]
I've made two separate setups of the ESP8266 and PN532 NFC. On one of them I left out the buzzer and light for now.
Both are connected through ESPHOME into home assistant. This setup seems to work.

By both don't detect any NFC tags. I also can't find any log entries about the NFC tag scan.
The switch #1 is up and the #2 is down on the NFC chip. The wiring I have:
GND --> GND
VCC --> 5V
SDA --> D1
SCL --> D2

But i've tried other combinations of wiring.

What is the best way to debug this?

**Comment by adonno** [comment]
connect the ESP to you Computer and check the logs , hit the restart button on the esp8266 an check if it displays an error while trying to detect PN532 at boot ?  

or just paste the logs here
