### ISSUE TITLE
Tagreader is not discoverd by ESPHome dashboard

### ISSUE THREAD

**Issue by arjenfvellinga** [adonno/tagreader#169]
Summary
I'm running Home Assistant (2022.5.5) and ESPHome dashboard (2022.5.1) isn't discovering my tagreader

I had Home Assistant running without the ESPHome add-on installed. Then I added a tag reader to my setup. I can't remember if it was discovered by Home Assistant or that I added it manually. But the result was a correctly configured tagreader as a ESPHome integration.

Recently, I purchased some smart plugs based on ESPHome and added the ESPHome add-on including the dashboard. The dashboard discoverd the smart plugs, but it didn't find the tagreader

Integration:
![image](https://user-images.githubusercontent.com/16539832/172157719-dcbac141-ccad-4ded-84cd-876fc55b6d95.png)

add-on
![image](https://user-images.githubusercontent.com/16539832/172157770-fbc7e1b3-c6e4-4303-b6d7-a30474a74dd1.png)

How can I have the dashboard also list the tagreader?

**Comment by riemers** [comment]
fyi, just configured mine, i don't see it either so might be "business as usual"

**Comment by adonno** [comment]
When did you get yours ? Or did you DIY it ?

**Comment by riemers** [comment]
> When did you get yours ? Or did you DIY it ?

Got mine at least multiple months ago. Found it again on the pile of “I want to use it but didn’t have time for it yet” 🤔 does have usb-c though.

**Comment by adonno** [comment]
oh wow sorry i missed replying to this thread 

can you guys flash it via https://adonno.github.io/tagreader

**Comment by arjenfvellinga** [comment]
I indeed flashed it, and it was found. So for me it works!
