### ISSUE TITLE
Type of buzzer - active or passive

### ISSUE THREAD

**Issue by martin131** [adonno/tagreader#172]
I'm not sure if I should use active or passive buzzer. The link goes to active version but ESPHome documentation says only passive version is supported - https://esphome.io/components/rtttl.html

I have already bought an active version. The sound works but it's a little weird I think.

**Comment by jamesmyatt** [comment]
I think it needs to be passive. It uses this component: https://esphome.io/components/rtttl.html

@adonno, probably worth being explicit in the Readme.
