### ISSUE TITLE
play music tag

### ISSUE THREAD

**Issue by rananna** [adonno/tagreader#198]
the blueprint seems to need a manufacture of expressif, ie: from the blueprint:
manufacturer: espressif
However, the tagreader has a manufacturer field of 
"by Adonno"
Hence the blueprint cannot select the tagreader as a device.

**Comment by luka6000** [comment]
I’ve created pull request to correct this
https://github.com/adonno/tagreader/pull/199

**Comment by adonno** [comment]
I have updated the yaml
