### ISSUE TITLE
1 tag + 2 separate tagreaders = different automations?

### ISSUE THREAD

**Issue by dhuddle** [adonno/tagreader#200]
I bought two of these and they are fantastic! I love these devices!

My use case: I have the tag readers deployed near entrances. I want the same tag to do different things based on which reader that scans it. How can that be done easily via automations?

Example: tag #1 scanned on reader #1 = open front door. Tag #1 scanned on reader #2 = open inner door.

I was thinking the tag reader light maybe could be used as a condition? Any ideas for an actually elegant way to do this?

**Comment by adonno** [comment]
hello this has been already replied here  https://github.com/adonno/tagreader/discussions/131
