### ISSUE TITLE
[ Question ] Humidity and power consuming.

### ISSUE THREAD

**Issue by 7system7** [adonno/tagreader#206]
Firstly, thank you for your work! I have some question to ask.

1. Is there any way to use this outside environment? I would like to use this to open a garden door. The problem is that, sometimes there is 85-95% of humidity where I live.
2. Another thing, I would use this remotely. So I would use i.e. a 20 000 mAh power bank as a power supply. I need your opinion is it worth or not. :) Will it drain the power bank in a couple of day or not?

Thank you for your time in advance.

**Comment by adonno** [comment]
1. not sure about humidity but you could stick the case in a Tupperware box . I haven't foreseen a fully waterproof version yet. 
2. 20.000 mAh could last you 2-3 days. Not a viable solution.  i am still prototyping a battery version that shuts itself off and can be restarted with a button

**Comment by 7system7** [comment]
Thank you for your answer!

**Comment by brechtvhb** [comment]
Wouldn't it be possible to add a proximity sensor, which could turn on the NFC reader and wifi when someone is nearby, instead of using a button for the battery version?
