### ISSUE TITLE
Can't read NFC-Tags

### ISSUE THREAD

**Issue by BjGoCraft** [adonno/tagreader#226]
Hi,
Everything is connected right (I tested every connection with a multimeter). The switch 1 on the reader module is on (up) and switch 2 off:
![20230220_232237](https://user-images.githubusercontent.com/124093178/220207890-c1f2c7de-055d-405e-9bd3-8bae447a1401.jpg)
![20230220_232132](https://user-images.githubusercontent.com/124093178/220207899-6326af49-bb96-4658-bda8-70125add65cd.jpg)
![20230220_232159](https://user-images.githubusercontent.com/124093178/220207905-a79e6185-415c-4c51-86ff-17f4067f1581.jpg)
![20230220_232225](https://user-images.githubusercontent.com/124093178/220207908-8fd60817-72fe-4b15-9d40-2cc306cee782.jpg)

The ESP is shown in HomeAssistant as a device of the service ESPHome. So the ESP is recognized. I once connected a LED to it and I could control it with the TagReaderLED switch within Home Assistant, so HomeAssistant can communicate with the ESP. But when I put a NFC-Card on the reader, there is no event in the logbook. The NFC-Card works fine with my smartphone (it's the one the Reader came with).

**Comment by bbrendon** [comment]
I was running a very old version of this project and mine was working until today when I updated it because I didn't have the LED and Buzzer enabled. 

For me, the esphome appears in hass but like you, the NFC reader no longer works. I'm not sure what specifically the issue is yet. I'm still trying to work it out.

**Comment by BjGoCraft** [comment]
For me it turned out to be bad soldering. Even though I checked every connection with a multimeter, resoldering the NFC-Reader to the cables did the job for me.

**Comment by bbrendon** [comment]
After some closer looking, mine is wired completely different. It looks like a lot has changed since I built mine. So I guess I find old firmware or re-wire it.

**Comment by chernerd** [comment]
@BjGoCraft when you re-soldered did you have to remove the jumper pins and directly solder the wires? How did you resolder?
