### ISSUE TITLE
ESPHome 2023.7 - Error at firmware update

### ISSUE THREAD

**Issue by Eyco1981** [adonno/tagreader#245]
With ESPHome 2023.7 the following error occurs.
It seems, the configuration in your repository needs to be changed.

```
INFO ESPHome 2023.7.0 
INFO Reading configuration /config/esphome/tagreader-7c1293.yaml... 

Failed config 

switch.template: [source /config/esphome/.esphome/packages/fa8076cc/tagreader.yaml:56] 
platform: 
template name: TagReader Buzzer Enabled 
id: buzzer_enabled icon: 
mdi:volume-high 
optimistic: True 
The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
restore_state: True 
entity_category: config 

switch.template: [source /config/esphome/.esphome/packages/fa8076cc/tagreader.yaml:63] 
platform: template 
name: TagReader LED enabled 
id: led_enabled icon: mdi:alarm-light-outline 
optimistic: True 
The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
restore_state: True 
entity_category: config
```

**Comment by Masterz69** [comment]
> 

Remove ```restore_state``` from template switches.
Specify ```restore_mode``` if not defined yet.

**Comment by jakevis** [comment]
yeah running into this issue as well - cant work out how to override the template - but I guess ideally this needs to be updated in https://github.com/adonno/tagreader/blob/master/tagreader.yaml

**Comment by howesey2k** [comment]
I agree for it to be looked at. I've deleted the references to restore_state and reinstalled it. Seems to be working but getting an error "Component pn532 took a long time for an operation"
Could this be looked at? Many thanks

**Comment by monstergubl** [comment]
hey got the same problem did you get a solution ?

**Comment by waazdakka** [comment]
Hello,
I just flashed again my tagreader with the actual yaml but I still get the 
"Component pn532 took a long time for an operation (0.10 s).
[W][component:205]: Components should block for at most 20-30ms." error. 
Don't know what to change to make this error disappear :'(

**Comment by howesey2k** [comment]
I get the same error. I think it's still working with this error but please
check too. I think someone mentioned in a forum post that it's possibly an
ESPHome issue. Might be worth mentioning it on their forums. The firmware
update fixed a different issue which stopped the device from working.

**Comment by titis14** [comment]
Hi,
I still get the error even though I have the latest version.

**Comment by howesey2k** [comment]
What error you getting exactly?

**Comment by titis14** [comment]
This mistake.
[11:50:41][W][component:204]: Component pn532 took a long time for an operation (0.10 s).
[11:50:41][W][component:205]: Components should block for at most 20-30ms.
For a while now my tagreader has not been able to read badges. I made a topic here but no one replied.
https://github.com/adonno/tagreader/issues/241
I don't know if it's related to this error. I have this project and for several months at my club people can no longer deactivate the alarm easily.
Thanks

**Comment by howesey2k** [comment]
Did you copy and paste the yaml update that adonno released? This fixed my
tags from reading. You need to copy and the paste the new yaml into the
correct file. Then click install again. This won't fix the timeout issue in
the logs but should fix the tags from not scanning. If this doesn't work,
try reaching out again and see if someone else can help you like a
developer :) If you are unsure where to copy and paste the yaml, I'll see
if I can remember haha

**Comment by titis14** [comment]
On ESPHome I clicked on edited and I put the new yaml then installed by wifi.

**Comment by howesey2k** [comment]
It's actually in a folder on your machine you need to navigate to. Do you
use a file editor plug in?

**Comment by titis14** [comment]
No, I didn't do it through a file editor. On Home Assistant I use Studio Core Server, would you tell me which file to modify? Thanks

**Comment by howesey2k** [comment]
I navigated to the yaml file by
esphome/.esphome/packages/name of tag reader package/Tagreader.yaml


I then copied Adonos code and pasted it into that yaml then clicked install
on the esphome integration

**Comment by titis14** [comment]
Thank you in this way I am well in v1.4 :(

**Comment by howesey2k** [comment]
Did this work?

**Comment by titis14** [comment]
I think I know why it doesn't work anymore. Indeed I had to use the smart home junkie file.
dashboard_import:
   package_import_url: github://smarthomejunkie/tagreader/tagreader.yaml
In my editor I see that the file is not up to date.
I modified the file but when I want to validate it in ESPHome I have errors. I also have 2 folder for the tag.
Is there a way to erase everything and start from scratch?
I do all this remotely because I don't have the ESP near me.

**Comment by howesey2k** [comment]
I was once given this link
https://adonno.github.io/tagreader

Plug it into the usb on your pc and use edge, chrome has never worked for
me.

If this doesn't work, not sure how to help sorry.

**Comment by titis14** [comment]
Ok thanks you have already put on a track.
I'm going to do a new ESP and we'll see.

**Comment by howesey2k** [comment]
Any joy?
