### ISSUE TITLE
Breaking Change in OTA version ESPHome 2024.6.0 - 19th June 2024

### ISSUE THREAD

**Issue by Cozzman2k** [adonno/tagreader#264]
OTA breaking change was made, depreciating OTA safe mode and REQUIRING platform be specified

See change:
https://next.esphome.io/changelog/2024.6.0.html#ota-platforms

See new requirement
# Old
#ota:

#ota:
  password: "xxxx"

# New
ota:
  platform: esphome

ota:
  platform: esphome
  password: "xxxx"

**Comment by adonno** [comment]
fixed here 

https://github.com/adonno/tagreader/commit/20bd39d7ee6d8cb0a9067ddc37a54a7c424719dc
