### ISSUE TITLE
 Component pn532 is marked FAILED

### ISSUE THREAD

**Issue by bksolo** [adonno/tagreader#269]
on home assistant esphome. try to install the tagreader pn532 with esp6822 d1 mini.

Took the tagreader.yaml 

[22:19:16][C][pn532:431]: PN532:
[22:19:16][C][pn532:443]:   Update Interval: 1.0s
[22:19:16][C][pn532_i2c:125]:   Address: 0x24
[22:19:16][E][component:082]:   Component pn532 is marked FAILED

The hardware setup should be ok - pn532 dip-switch is on I2C.

Any idea what this could be, can't find anything on the internet.

**Comment by tim-vk** [comment]
Wait, so what did you do? Just threw away all your hardware and tried again?

**Comment by boonusss** [comment]
Having the exact same issue. ESP32 WROOM 32 and ESP32 C3 Supermini. Switches are OK in I2C. Tried also SPI no luck. Same error. Now im blaming the pn532 module, but I have two. Tried both.
