### ISSUE TITLE
Component Links Not Working

### ISSUE THREAD

**Issue by codeclinic** [adonno/tagreader#37]
The Aliexpress links for the device components are invalid.

Can these be replaced with working ones?

**Comment by adonno** [comment]
I've had several people try and no one had an issue with the links working. 
These are Ali-express affiliate links that might get blocked by an adblocker of some kind. 

Will ad note in the readme.

**Comment by tdroza** [comment]
The links work, but (for me) were blocked by PiHole which sees the affiliate links as ads.
