### ISSUE TITLE
LED when writing

### ISSUE THREAD

**Issue by adonno** [adonno/tagreader#39]
we should make use of the LED when the tag reader is in write mode. 
The LED could be red to indicate that it will write.

**Comment by magnusoverli** [comment]
Great idea!

**Comment by dudu631** [comment]
How do you set it on write mode?

**Comment by adonno** [comment]
> How do you set it on write mode?

Not there yet but once we are there this will be part of this

**Comment by adonno** [comment]
Solved write mode can be achieved by calling a service in ha
