### ISSUE TITLE
Inform that NDEF will replace UID when present 

### ISSUE THREAD

**Issue by adonno** [adonno/tagreader#40]
Whenever a tag with a NDEF is scanned,  check if there is an automation for that tag, and if so, replace the UID by NDEF in the automation 

This is to avoid that a Tag would trigger 2 automations (one based on the NDEF another on the UID) at once. If users want to have a different action based on the device they use to read the tag, they will have to set it up by device.

Not sure if this should be managed on Home-Assistant side though

**Comment by balloob** [comment]
We shouldn't do this. If NDEF available, we fire NDEF. Adding something like this would only make it more complicated for users in the end.

**Comment by adonno** [comment]
This would then be a breaking change for users who have already set up an automation based on UID then ?

**Comment by balloob** [comment]
But they flashed an NDEF value on it themselves?

**Comment by adonno** [comment]
ok makes 100% sense, will have to be mentioned in the release notes.
