### ISSUE TITLE
Discord links in README.md don't work

### ISSUE THREAD

**Issue by tdroza** [adonno/tagreader#43]
The new discord links added by [PR 36](https://github.com/adonno/tagreader/pull/36) don't work:

1. The badges just link to a static "Chat xx online" image and don't open discord

1. The discord link (https://discord.gg/ZsfSyj) under the Discord heading doesn't work for me. Is this the correct link?

**Comment by tdroza** [comment]
I'm happy to create a fix for this if someone can provide the correct Discord link.

**Comment by jesserockz** [comment]
Thanks @tdroza I have updated the links and the badge. Looks like the original link had an expiry. New one doesn't
