### ISSUE TITLE
Cannot buy a reader

### ISSUE THREAD

**Issue by kyotodesertfox** [adonno/tagreader#5]
It appears that your Cart may not be working correctly. When I select the item + colors of the reader, and then add to cart, it takes me to the Cart, which says it is empty.

Are there other ways of purchasing a reader?

**Comment by magnusoverli** [comment]
Hey! There are currently some technical issues with the cart. We are working on it and hope to have a solution soon. For now, please leave Andrea a message on Twitter, and he will be in touch.

**Comment by kyotodesertfox** [comment]
Great! I will keep an eye on things.

Glad you guys are already aware!

**Comment by adonno** [comment]
Here is the new backup store https://adonno-crafts.myshopify.com/

**Comment by kyotodesertfox** [comment]
@adonno - in the description:

> (does not work with the mobile phone apps)

What specifically does this mean?

**Comment by adonno** [comment]
HA mobile apps can write tags to be used with the phones the reader uses the tag ID (for now), some tags are versatile and can do both, the tags I got unfortunately are read-only it seems

**Comment by kyotodesertfox** [comment]
I went ahead and submitted an order; look forward to playing with some new toys!
