### ISSUE TITLE
The Buzzer doesn't beep when scan a tag

### ISSUE THREAD

**Issue by CarpeDiemRo** [adonno/tagreader#55]
The buzzer play rtttl when API succesffully initialized.

The buzzer doesn't emit any sound when I scan any card. Maybe I missed something.

**Comment by adonno** [comment]
You have to enable it in Home-Assistant  
Integrations --> esphome

**Comment by CarpeDiemRo** [comment]
Oh, sorry. My bad. I forgot about the switch.

It works.
