### ISSUE TITLE
Scan "transmission" intermittency

### ISSUE THREAD

**Issue by originalnr8** [adonno/tagreader#56]
I'm still breadboarding this out so have simple and easy reconfiguration. I'm using a NodeMCUv2 running the tagreader.yaml as provided (although the name is rfid_one). Otherwise it is the standard setup.

Plug in the USB and the logs on HA show no scanning. Odd so i connect the serial monitor and see the output start reeling. I am scanning the tags fine. It is the connection to HA that is the problem. So I watch more and notice that it is connecting to HA for about 7 seconds at a time. It is then staying disconnected for 10 to 70 seconds. I'm in the same room as my wifi access point so its not interference or signal loss.

If there is a power saving mode so once a tag is scanned the system wakes up and then sends adding a delay to the process but functioning i'd be happy as it would have worked (albeit slowly).

**Comment by adonno** [comment]
Hello have you had a look at #44 ?  That is explaining the Wifi issues and a new "dev version" of ESPHome with native support for I2C PN532
