### ISSUE TITLE
rfidreader_tag_ko

### ISSUE THREAD

**Issue by pacomm** [adonno/tagreader#58]
when does this run?

 ```
- service: rfidreader_tag_ko
    then:
    - rtttl.play: "beep:d=8,o=5,b=100:b"
```

I thought it might work if the tag is disabled in home assistant but there is no option for this

Thanks a lot

**Comment by jesserockz** [comment]
Currently never, its been there from the start of the project. The current beep that you get when scanning only indicates a successful scan. But you can call this service (and the other one) from HA if you want to call back after actually doing something with the tag data.
