### ISSUE TITLE
" Timed out waiting for readiness from PN532!"

### ISSUE THREAD

**Issue by sirvictory444** [adonno/tagreader#70]
Hello,
Changing the logger level to VERBOSE I can see the error message:  "Timed out waiting for readiness from PN532!"
If I use VERY_VERBOSE I can see "A component took a long time in a loop() cycle"
Card reads do not work.  If I hold the card over the NFC sensor for 5-10 seconds, eventually a read will come in.  
I've double checked the wiring, proper soldering, etc, thats not an issue.   I know the i2c version of this is still in the dev mode.
Do I have a bad board? I've tried with 2 different D1 minis, but only have the 1 PN532.
The hardware is in the 3d printed case from this repo.
My ESP board does not say AZ Delivery.
Thank You,

**Comment by RichieFrame** [comment]
Could be a bad reader board, I had 1 out of 3 not work out of the box, I was able to trace it to bad solder flow which joined 2 of the independent circuits on the board, because a component was off center by about 0.25mm when it was surface mount soldered

**Comment by adonno** [comment]
In this case it's the firmware 
I would suggest using the newest yaml in combination with ESPHome dev as explained on the Readme.md you'll have to resolder to I2C instead of SPI but it will run rock solid

**Comment by sirvictory444** [comment]
> In this case it's the firmware
> I would suggest using the newest yaml in combination with ESPHome dev as explained on the Readme.md you'll have to resolder to I2C instead of SPI but it will run rock solid

Yes, this is with I2C.  Using the latest firmware yaml, wiring, and dev version of ESPHome.   SDA & SCL wiring.  I suppose I'll order another board if you're saying it's not a software issue?

**Comment by adonno** [comment]
last question are the Jumpers set correctly?

**Comment by sirvictory444** [comment]
> last question are the Jumpers set correctly?

Yes, I0 on/up, I1 off/down.     Like I said, it does work once every 30 seconds maybe, in between getting random mismatched data.  I don't think it would do that unless it was set correct, no?  Maybe DIP switch is bad, I've seen that with even the larger through hole kind.  I'll try to use some thin wire to solder them, if I'm able to without messing it up.

**Comment by sirvictory444** [comment]
I ordered another board.  I suppose we can close this ticket, as we're saying it's probably a hardware issue.
