### ISSUE TITLE
correct photo for I2C

### ISSUE THREAD

**Issue by joopy** [adonno/tagreader#72]
sorry github is new for me. Find attached an correct picture:
![IMG_1601](https://user-images.githubusercontent.com/25509595/99439425-73df5400-2915-11eb-9721-5bf17de7da31.jpg)

**Comment by adonno** [comment]
Hello ,

Could you give me more details on this photo please ?

**Comment by joopy** [comment]
This photo is with I2C and correct dipswitch.
You can use it in your readme

Op di 17 nov. 2020 om 20:58 schreef Andrea Donno <notifications@github.com>

**Comment by CarpeDiemRo** [comment]
@joopy I didn't get it completely. Can you be, please, more specific.
