### ISSUE TITLE
REQUEST: Beep when read

### ISSUE THREAD

**Issue by omayhemo** [adonno/tagreader#80]
I heard an initialization beep from the unit, so I'm wondering if it can be made to beep when successfully read?

**Comment by adonno** [comment]
In Home-Assistant you should see a new device called tagreader_xxxxx in the ESPHome integrations
that Device exposes 3 entities. Turn the "loudspeaker" on and it will beep at every scan

**Comment by omayhemo** [comment]
You rock!
