### ISSUE TITLE
Which WS2812 ?

### ISSUE THREAD

**Issue by bsrdjan** [adonno/tagreader#90]
The WS2812 offers following alternatives:

- SK6812 RGB WW
- WS2812B White
- WS2812B Black
- SK6812 RGB W
- SK6812 NWW

What are the differences, which one to use for my 1st reader?

**Comment by martinosk** [comment]
You need the RGB version. That would be WS2812B White or WS2812B Black, depending if you like your PCB to be white or black.

**Comment by bsrdjan** [comment]
Many thanks @martinosk
